# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bookworm"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bookworm"
  armhf: "ghcr.io/home-assistant/armhf-base-debian:bookworm"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:bookworm"
  i386: "ghcr.io/home-assistant/i386-base-debian:bookworm"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Duplicati add-on"
  org.opencontainers.image.description: "EStore securely encrypted backups on cloud storage services!."
  org.opencontainers.image.source: "https://github.com/adrianoamalfi/hassos-addons/"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
  DUPLICATI_VERSION: "2.0.8.1-1"