# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:6.2.5
  amd64: ghcr.io/hassio-addons/debian-base/amd64:6.2.5
  armhf: ghcr.io/hassio-addons/debian-base/armhf:6.2.5
  armv7: ghcr.io/hassio-addons/debian-base/armv7:6.2.5
  i386: ghcr.io/hassio-addons/debian-base/i386:6.2.5
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Duplicati add-on"
  org.opencontainers.image.description: "Duplicati add-on Backup Software."
  org.opencontainers.image.source: "https://github.com/adrianoamalfi/hassos-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
